FROM rustembedded/cross:armv7-unknown-linux-musleabihf-0.1.16

RUN apt-get update \
  && apt-get install -y --no-install-recommends gnupg \
  && rm -rf /var/lib/apt/lists/*

COPY install-git.sh /
RUN bash install-git.sh
